/*
  ==============================================================================

    PlaylistAggregateComponent.h
    Created: 12 Aug 2020 9:59:38pm
    Author:  david

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>
#include "PlaylistGrid.h"
#include "PlaylistToolbar.h"
#include "ExternalCallbackActionListener.h"
#include "ExternalCallbackTextEditorListener.h"

//==============================================================================

/// <summary>
/// Aggregate UI component, controlling all the UI parts necessary for the Playlist to work
/// </summary>
class PlaylistAggregateComponent  :
	public juce::Component,
    public TextEditor::Listener

{
public:
    PlaylistAggregateComponent();
    ~PlaylistAggregateComponent() override;

	//Overloads for the virtual methods inherited by the Component class
    void paint (juce::Graphics&) override;
    void resized() override;

	//Callbacks for the events generated by the playlist toolbar
	//Calback invoked when the Add File button is pressed
    void AddFileCallback(const String& message);
    //Calback invoked when the Add Folder button is pressed
    void AddFolderCallback(const String& message) const;
    //Calback invoked when the Delete File button is pressed
    void DeleteFilesCallback(const String& message);
    //Calback invoked when the Load Playlist button is pressed
    void LoadPlaylistCallback(const String& message);
    //Calback invoked when the Save Playlist button is pressed
    void SavePlaylistCallback(const String& message) const;
    //Calback invoked when the Open File in Player button is pressed
    void OpenFileInPlayerCallback(const String& message);

    //Calback invoked when an item in the grid is double-clicked
    void ItemDoubleClickedCallback(const String& message) const;
    //Calback invoked when the some text is added to the search field
    void SearchTextChangedCallback(const String& message);

	//Broadcaster to notify the selection of a track from the playlist
    ActionBroadcaster TrackSelectedToPlayEventBroadcaster;
private:
    //Name of the folder containing the application data
    const static String APPFOLDERNAME;
	//Name of the playlist file extension
    const static String PLAYLISTFILEEXTENSION;
	//Full path of the folder containing the application data.
	//This is where the playlist files are saved
    const static String APPFOLDERFULLPATH();

	//Component displaying the Playlist grid
    PlaylistGrid playlistGrid;
	//Component displaying the Playlist toolbar
    PlaylistToolbar playlistToolbar;
	//Component displaying the Text field to search for files in the playlist
    TextEditor searchBox;

	//Listeners for events generated by the Playlist Toolbar
	//Listener for the Add File Event
    ExternalCallbackActionListener AddFileListener;
    //Listener for the Add Folder Event
    ExternalCallbackActionListener AddFolderListener;
    //Listener for the Delete File Event
    ExternalCallbackActionListener DeleteFilesListener;
    //Listener for the Load Playlist Event
    ExternalCallbackActionListener LoadPlaylistListener;
    //Listener for the Save Playlist Event
    ExternalCallbackActionListener SavePlaylistListener;
    //Listener for the Open File In Player Event
    ExternalCallbackActionListener OpenFileInPlayerListener;

    //Listener for the double-click event on an item in the grid
    ExternalCallbackActionListener ItemDoubleClickedListener;

    //Listener for the change of text in the search text field
    ExternalCallbackTextEditorListener searchTextChangedListener;
	
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (PlaylistAggregateComponent)
};
